# Generated by Django 5.2.6 on 2025-12-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CORAH", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
